# Generated by Django 5.1.7 on 2025-03-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(max_length=200),
        ),
    ]
