# Generated by Django 5.1.7 on 2025-03-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaiconvsession",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("developer", "Developer"),
                    ("system", "System"),
                ],
                max_length=10,
            ),
        ),
    ]
