# Generated by Django 5.1.7 on 2025-03-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_alter_openaiconvsession_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("hi", "Hindi"),
                    ("fr", "French"),
                    ("ne", "Nepali"),
                    ("ge", "German"),
                    ("ja", "Japanese"),
                ],
                max_length=20,
            ),
        ),
    ]
