# Generated by Django 5.1.7 on 2025-03-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_alter_userpreference_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("hi", "Hindi"),
                    ("fr", "French"),
                    ("ne", "Nepali"),
                    ("ge", "German"),
                    ("ja", "Japanese"),
                    ("bg", "Bulgarian"),
                    ("hu", "Hungarian"),
                ],
                max_length=20,
            ),
        ),
    ]
